INSERT INTO TB_FORMS_OF_PAYMENT(CAN_PARCEL, NAME) VALUES(FALSE, 'Boleto Bancário');
INSERT INTO TB_FORMS_OF_PAYMENT(CAN_PARCEL, NAME) VALUES(TRUE, 'Cartão de Crédito');
INSERT INTO TB_FORMS_OF_PAYMENT(CAN_PARCEL, NAME) VALUES(FALSE, 'PIX');